import type { Restaurant, MenuItem, User } from "./app-context"

export const mockUsers: User[] = [
  {
    id: "user_1",
    name: "Cliente Demo",
    email: "customer@example.com",
    role: "customer",
  },
  {
    id: "user_2",
    name: "Andrés (Restaurante)",
    email: "restaurant@example.com",
    role: "restaurant",
    restaurantId: "rest_1",
  },
  {
    id: "user_3",
    name: "Administrador",
    email: "admin@example.com",
    role: "admin",
  },
]

export const mockRestaurants: Restaurant[] = [
  {
    id: "rest_1",
    name: "Andrés Carne de Res",
    description: "Carne a la parrilla de alta calidad con ambiente tradicional colombiano",
    rating: 4.9,
    deliveryTime: 45,
    deliveryFee: 3.99,
    cuisine: ["Colombiano", "Carnes"],
    isOpen: true,
    image: "/bustling-pizzeria.png",
  },
  {
    id: "rest_2",
    name: "Harry's Pizza",
    description: "Pizzas tradicionales con ingredientes de primera calidad",
    rating: 4.7,
    deliveryTime: 30,
    deliveryFee: 2.99,
    cuisine: ["Pizza", "Italiano"],
    isOpen: true,
    image: "/burger-restaurant.png",
  },
  {
    id: "rest_3",
    name: "Rostipollo",
    description: "Pollo a la brasa criollo, las costillas y alitas más sabrosas",
    rating: 4.8,
    deliveryTime: 25,
    deliveryFee: 2.49,
    cuisine: ["Colombiano", "Pollo"],
    isOpen: true,
    image: "/bustling-sushi-restaurant.png",
  },
  {
    id: "rest_4",
    name: "Frisby",
    description: "Pollo frito crujiente con salsas y acompañamientos deliciosos",
    rating: 4.6,
    deliveryTime: 20,
    deliveryFee: 1.99,
    cuisine: ["Comida Rápida", "Pollo"],
    isOpen: true,
    image: "/vibrant-taco-restaurant.png",
  },
  {
    id: "rest_5",
    name: "Carrefour Food Court",
    description: "Variedad de opciones gastronómicas en un solo lugar",
    rating: 4.5,
    deliveryTime: 35,
    deliveryFee: 2.99,
    cuisine: ["Variado", "Comida Rápida"],
    isOpen: true,
    image: "/pizza-place.png",
  },
  {
    id: "rest_6",
    name: "Justo & Bueno",
    description: "Comidas caseras y productos frescos a precios justos",
    rating: 4.4,
    deliveryTime: 30,
    deliveryFee: 1.99,
    cuisine: ["Colombiano", "Comida Casera"],
    isOpen: true,
    image: "/taco-stand.png",
  },
]

export const mockMenuItems: MenuItem[] = [
  // Andrés Carne de Res
  {
    id: "item_1",
    name: "Carne Asada Especial",
    description: "Filete de res premium a la parrilla con papas y yuca",
    price: 35.99,
    category: "Carnes",
    rating: 4.9,
    restaurantId: "rest_1",
    image: "/margherita-pizza.png",
  },
  {
    id: "item_2",
    name: "Costillas BBQ",
    description: "Costillas ahumadas con salsa casera",
    price: 32.99,
    category: "Carnes",
    rating: 4.8,
    restaurantId: "rest_1",
    image: "/pepperoni-pizza.png",
  },
  // Harry's Pizza
  {
    id: "item_3",
    name: "Pizza Hawaiana",
    description: "Jamón, piña, queso mozzarella fresca",
    price: 18.99,
    category: "Pizzas",
    rating: 4.7,
    restaurantId: "rest_2",
    image: "/classic-burger.png",
  },
  {
    id: "item_4",
    name: "Pizza de Champiñones",
    description: "Champiñones frescos, queso y especias",
    price: 16.99,
    category: "Pizzas",
    rating: 4.6,
    restaurantId: "rest_2",
    image: "/spicy-tuna-roll.png",
  },
  // Rostipollo
  {
    id: "item_5",
    name: "Pollo a la Brasa Completo",
    description: "Medio pollo a la brasa con papas y ensalada",
    price: 19.99,
    category: "Pollos",
    rating: 4.8,
    restaurantId: "rest_3",
    image: "/chicken-tacos.png",
  },
  {
    id: "item_6",
    name: "Alitas BBQ",
    description: "Alitas crujientes con salsa BBQ casera",
    price: 14.99,
    category: "Pollos",
    rating: 4.7,
    restaurantId: "rest_3",
    image: "/alitasbbq.png",
  },
  // Frisby
  {
    id: "item_7",
    name: "Combo Familiar",
    description: "8 piezas de pollo, papas y bebida para 4 personas",
    price: 45.99,
    category: "Combos",
    rating: 4.6,
    restaurantId: "rest_4",
    image: "/combofamilia.jpeg",
  },
  // Carrefour Food Court
  {
    id: "item_8",
    name: "Arepa con Queso",
    description: "Arepa recién hecha rellena de queso fresco",
    price: 4.99,
    category: "Arepas",
    rating: 4.5,
    restaurantId: "rest_5",
    image: "/arepa-con-queso.png",
  },
  // Justo & Bueno
  {
    id: "item_9",
    name: "Bandeja Paisa",
    description: "Típico plato colombiano con carnes y acompañamientos",
    price: 22.99,
    category: "Comida Colombiana",
    rating: 4.4,
    restaurantId: "rest_6",
    image: "/bandejita.jpeg",
  },
]
